### ISSUE TITLE
which-key support or a way to add keymaps separately 

### ISSUE THREAD

**Issue by s1n7ax** [ziontee113/neo-minimap#1]
I would like to have a way to add the treesitter queries without having to register a keymap. Based on the filetype, it will show the relevant captures.

```
nm.set('filetype', {
    query = [[
        ;; query
        ((query_goes_here) @cap)
    ]],
})

wk.register({
    ['<leader>'] = {
        n = { nm.open, 'Open mini map' }
        ... = ... other keymaps
    }
})
```

**Comment by ziontee113** [comment]
Oh, you mean you want a Lua function to open minimap?

**Comment by ziontee113** [comment]
You can try:
```lua
nm.browse(opts)
```

Example:
```lua
nm.browse({
	query = [[
;; query
((for_statement) @cap)
((function_declaration) @cap)
  ]],
	search_patterns = {
		{ "function", "<C-j>", true },
		{ "function", "<C-k>", false },
	},
})
```
Please tell me what you think. Is this good enough for your use case? If so, can you tell me the details of your use case? Thank you.

**Comment by ziontee113** [comment]
Hi @s1n7ax I'm closing the issue for now due to inactivity. Please feel free to open it if you have further issues regarding the `browse()` method.
