### ISSUE TITLE
Displaying multiline matches in the minimap?

### ISSUE THREAD

**Issue by mikowitz** [ziontee113/neo-minimap#16]
I'm building up a set of treesitter queries for using neo-minimap in Rust. I'm not sure how familiar you are with the language, but in modules, test functions are marked by an attribute:

```rust
#[test]
fn this_does_something() {
    ...
}
```

I've built a query that I believe captures this

```clojure
(((attribute_item) @attr (function_item) @cap (#vim-match? @attr "test")))
```

but in the minimap window, I only see the first line of each match, so it looks like

```
89      #[test]
97      #[test]
103     #[test]
etc...
```

I haven't found an obvious (or any) way to specify which line (or maybe more simply all the lines) of a multiline match a rule should display in the minimap window, so I have two and a half questions:

1. given the way you've designed this plugin, would this be possible?
2. does a way already exist?

If the answer to both is yes, any guidance you can offer on how to configure my rules would be very welcome.
If the answer to 1 is yes but 2 is a no, unless this is something you're actively working on I'd be happy to try to write a patch to add that functionality.
If the answer to 1 is no, then I will figure out a workaround for my use case, and thank you for building a tool that gets me 99% of the way to where I want to be!

**Comment by ziontee113** [comment]
Hi @mikowitz , thank you for opening the issue.

I'll probably rewrite the whole plugin soon, but in the mean time, I've added some changes that will make your query work as you expected. The plugin will now prioritize the capture groups named "cap".

Please update your plugin to receive the change.

**Comment by mikowitz** [comment]
@ziontee113 thank you so much for your quick response and solution. That's perfect!
