### ISSUE TITLE
use of neo-minimap in .tex files

### ISSUE THREAD

**Issue by davidlunafn** [ziontee113/neo-minimap#3]
Hi, I am trying to run the plugin in *.tex files but I have the following error "E490: no fold found", any suggestion?, in other languages it works fine

**Comment by ziontee113** [comment]
Well, that errors occurs when you try pressing "zo" right? Can you give me the .set function to inspect it?

**Comment by davidlunafn** [comment]
![image](https://user-images.githubusercontent.com/28846713/197272786-8dd24803-0e20-41b7-9db8-8a5e27ca4652.png)

Yes, when I press "zo" I get that error, with "zu" it doesn't work but the error doesn't come out, I guess it must be a problem with my queries?

**Comment by ziontee113** [comment]
Hi @davidluna-fn , please update the plugin. The issue should be resolved.

**Comment by davidlunafn** [comment]
works perfect, thanks. the plugin is great
