### ISSUE TITLE
Want a global setting

### ISSUE THREAD

**Issue by uimataso** [ziontee113/neo-minimap#4]
I could like to have a global setting for things like `height_toggle`, `win_opts`, etc. You know, this will be convenient.

**Comment by ziontee113** [comment]
Sure. I'll implement it soon :)

**Comment by ziontee113** [comment]
Hi @luck07051 , please update the plugin. You should be able to call `nm.setup_defaults({opts})` to setup your default options.

**Comment by uimataso** [comment]
Thanks! Works for me.
Really good plugin. :+1:
