### ISSUE TITLE
throws error if search not found

### ISSUE THREAD

**Issue by desdic** [ziontee113/neo-minimap#7]
very nice plugin ! I did find a small error when using search patterns that does not exists

E5108: Error executing lua: ...e/pack/packer/start/neo-minimap/lua/neo-minimap/init.lua:292: Vim:E486: Pattern not found: function
stack traceback:
        [C]: in function 'cmd'
        ...e/pack/packer/start/neo-minimap/lua/neo-minimap/init.lua:292: in function <...e/pack/packer/start/neo-minimap/lua/neo-minimap/init.lua:289>

if I define search patterns and they do not exist and I use the search patterns its throwing an error
```
     search_patterns = {
         {"function", "<C-j>", true}, {"function", "<C-k>", false},
         {"keymap", "<A-j>", true}, {"keymap", "<A-k>", false}
     },
```

**Comment by ziontee113** [comment]
Hi @desdic , please update your plugin to receive the fix. Instead of throwing an error like before, now it should only print "Pattern not found". If the issue still persists, please feel free to give me feedback :+1:

**Comment by desdic** [comment]
> Hi @desdic , please update your plugin to receive the fix. Instead of throwing an error like before, now it should only print "Pattern not found". If the issue still persists, please feel free to give me feedback +1

it works perfectly thank you :) this plugin has become one of my favorites so please continue to good work! :)
