### ISSUE TITLE
Typo in 'disable_indentaion' option

### ISSUE THREAD

**Issue by woosaaahh** [ziontee113/neo-minimap#9]
Hi !

I noticed a typo in the option name : disable_indentaion > disable_indenta**t**ion

If needed, I fixed it on my fork here in the `fix-typo_disable_indentaoin` branch [here](https://github.com/woosaaahh/neo-minimap/commit/a7e991ac8f51574f8e71b973fd667f434c33196a).

**Comment by ziontee113** [comment]
Hi @woosaaahh , I've made a quick fix in 970a39d915602ee2a429540cc6b62ccaf29e4287. Thank you for bringing this to my attention :+1:
